// Menu data — Tavernaki restaurant
// 8 categories, 85 dishes
// Prices in лв (BGN). Bulgarian descriptions exactly as provided; English descriptions are translations.
window.menuData = [

  // ── САЛАТИ ────────────────────────────────────────────────────────────────

  {
    id:            'selska-salata',
    category:      'salads',
    name_bg:       'Селска салата',
    name_en:       'Village Salad',
    price:         11.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'домат, краставица, чушка, лук, маслини, сирене фета, магданоз, риган, каперси',
    description_en:'tomato, cucumber, pepper, onion, olives, feta cheese, parsley, oregano, capers',
    allergens:     ['milk'],
    image:         'menu-images/Селска Салата.png',
  },
  {
    id:            'salata-zele-s-morkovi',
    category:      'salads',
    name_bg:       'Салата зеле с моркови',
    name_en:       'Cabbage & Carrot Salad',
    price:         8.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'зеле, моркови, целина, чушка, дресинг',
    description_en:'cabbage, carrots, celery, pepper, dressing',
    allergens:     ['celery'],
    image:         'menu-images/Салата зеле с моркови.png',
  },
  {
    id:            'salata-dakos-krit',
    category:      'salads',
    name_bg:       'Салата Дакос крит',
    name_en:       'Dakos Crete Salad',
    price:         11.40,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'хлебче дакос, домат, натрошено сирене фета, маслини, риган',
    description_en:'dakos rusk bread, tomato, crumbled feta cheese, olives, oregano',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Салата Дакос крит.png',
  },
  {
    id:            'zelena-salata',
    category:      'salads',
    name_bg:       'Зелена салата',
    name_en:       'Green Salad',
    price:         12.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'марули, чери домат, сушени смокини, кедрови ядки, сирене манури, балсамов дресинг',
    description_en:'lettuce, cherry tomatoes, dried figs, pine nuts, manouri cheese, balsamic dressing',
    allergens:     ['milk', 'nuts'],
    image:         'menu-images/Зелена салата.png',
  },
  {
    id:            'salata-roka-s-halumi',
    category:      'salads',
    name_bg:       'Салата Рока с халуми',
    name_en:       'Arugula & Halloumi Salad',
    price:         14.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'марули, рукола, червено цвекло, сушени домати, катък, ябълка, гриловано халуми, орехи, цитрусов дресинг',
    description_en:'lettuce, arugula, red beet, sun-dried tomatoes, katiki cheese, apple, grilled halloumi, walnuts, citrus dressing',
    allergens:     ['milk', 'nuts'],
    image:         'menu-images/Салата Рока с халуми.png',
  },
  {
    id:            'salata-tsezar',
    category:      'salads',
    name_bg:       'Салата Цезар',
    name_en:       'Caesar Salad',
    price:         14.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'айсберг, крутони, бекон, пилешко филе, чери домат, пармезан, сос цезар',
    description_en:'iceberg lettuce, croutons, bacon, chicken fillet, cherry tomato, parmesan, Caesar dressing',
    allergens:     ['gluten', 'milk', 'fish'],
    image:         'menu-images/Салата Цезар.png',
  },
  {
    id:            'salata-greko-kapreze',
    category:      'salads',
    name_bg:       'Салата Греко капрезе',
    name_en:       'Greek Caprese Salad',
    price:         12.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домат, моцарела, рукола, босилеков дресинг',
    description_en:'tomato, mozzarella, arugula, basil dressing',
    allergens:     ['milk'],
    image:         'menu-images/Салата Греко капрезе.png',
  },
  {
    id:            'salata-s-morski-darove',
    category:      'salads',
    name_bg:       'Салата с морски дарове',
    name_en:       'Seafood Salad',
    price:         23.90,
    price_unit:    null,
    weight:        '450 г',
    description_bg:'марули, айсберг, чери домати, пармезан, скариди, калмари, балсамов дресинг',
    description_en:'lettuce, iceberg, cherry tomatoes, parmesan, shrimp, calamari, balsamic dressing',
    allergens:     ['milk', 'crustaceans', 'molluscs'],
    image:         'menu-images/Салата с морски дар.png',
  },
  {
    id:            'salata-s-pecheni-chushki',
    category:      'salads',
    name_bg:       'Салата с печени чушки',
    name_en:       'Roasted Pepper Salad',
    price:         12.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домати, печени чушки, сирене фета, червен лук, риган, дресинг',
    description_en:'tomatoes, roasted peppers, feta cheese, red onion, oregano, dressing',
    allergens:     ['milk'],
    image:         'menu-images/Салата с печени чушки.png',
  },
  {
    id:            'kinoa-i-skaridi',
    category:      'salads',
    name_bg:       'Киноа и скариди',
    name_en:       'Quinoa & Shrimp Salad',
    price:         18.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'киноа, скариди, чери домати, моркови, авокадо, крутони, дресинг',
    description_en:'quinoa, shrimp, cherry tomatoes, carrots, avocado, croutons, dressing',
    allergens:     ['gluten', 'crustaceans'],
    image:         'menu-images/Киноа и скариди.png',
  },
  {
    id:            'redena-salata',
    category:      'salads',
    name_bg:       'Редена салата',
    name_en:       'Arranged Salad',
    price:         16.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домати, лук, сирене, челена и червена чушка, краставици, маслини, плочка сирене',
    description_en:'tomatoes, onion, cheese, green and red pepper, cucumbers, olives, a slice of cheese',
    allergens:     ['milk'],
    image:         'menu-images/Редена салата.png',
  },
  {
    id:            'salata-sas-spanak',
    category:      'salads',
    name_bg:       'Салата със спанак',
    name_en:       'Spinach Salad',
    price:         12.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'спанак, натрошено сирене фета, пресен лук, копър, медени корички',
    description_en:'spinach, crumbled feta cheese, fresh onion, dill, honey-crusted bites',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Салата със спанак.png',
  },

  // ── СТАРТЕРИ ──────────────────────────────────────────────────────────────

  {
    id:            'feta-v-hrupkava-korichka',
    category:      'starters',
    name_bg:       'Фета сирене обвито в хрупкава коричка с орехи и мед',
    name_en:       'Feta in Crispy Pastry with Walnuts & Honey',
    price:         12.80,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'сирене фета, тестена обвивка, мед, сусам, орехи',
    description_en:'feta cheese, crispy pastry wrap, honey, sesame, walnuts',
    allergens:     ['gluten', 'milk', 'sesame', 'nuts'],
    image:         'menu-images/Фета сирене обвито в хрупкава коричка с орехи и мед.png',
  },
  {
    id:            'feta-s-zehtin-i-rigan',
    category:      'starters',
    name_bg:       'Фета сирене със зехтин и риган',
    name_en:       'Feta Cheese with Olive Oil & Oregano',
    price:         7.90,
    price_unit:    null,
    weight:        '100 г',
    description_bg:'сирене фета, зехтин, риган',
    description_en:'feta cheese, olive oil, oregano',
    allergens:     ['milk'],
    image:         'menu-images/Фета сирене със зехтин и риган.png',
  },
  {
    id:            'grilovano-halumi',
    category:      'starters',
    name_bg:       'Гриловано Халуми',
    name_en:       'Grilled Halloumi',
    price:         10.90,
    price_unit:    null,
    weight:        '150 г',
    description_bg:'сирене халуми, балсамов дресинг, чери домати',
    description_en:'halloumi cheese, balsamic dressing, cherry tomatoes',
    allergens:     ['milk'],
    image:         'menu-images/Гриловано Халуми.png',
  },
  {
    id:            'lyuti-chushki',
    category:      'starters',
    name_bg:       'Люти чушки',
    name_en:       'Hot Peppers',
    price:         5.50,
    price_unit:    null,
    weight:        '100 г',
    description_bg:'люти чушки, зехтин, оцет, магданоз',
    description_en:'hot peppers, olive oil, vinegar, parsley',
    allergens:     [],
    image:         'menu-images/Люти чушки.png',
  },
  {
    id:            'dzadziki',
    category:      'starters',
    name_bg:       'Дзадзики',
    name_en:       'Tzatziki',
    price:         8.60,
    price_unit:    null,
    weight:        '180 г',
    description_bg:'кисело мляко, краставица, чесън, копър, зехтин',
    description_en:'yogurt, cucumber, garlic, dill, olive oil',
    allergens:     ['milk'],
    image:         'menu-images/Дзадзики.png',
  },
  {
    id:            'tirokafteri',
    category:      'starters',
    name_bg:       'Тирокафтери',
    name_en:       'Tirokafteri (Spicy Feta Dip)',
    price:         8.60,
    price_unit:    null,
    weight:        '180 г',
    description_bg:'сирене фета, люта чушка, зехтин',
    description_en:'feta cheese, hot pepper, olive oil',
    allergens:     ['milk'],
    image:         'menu-images/Тирокафтери.png',
  },
  {
    id:            'tarama',
    category:      'starters',
    name_bg:       'Тарама',
    name_en:       'Tarama (Fish Roe Dip)',
    price:         8.60,
    price_unit:    null,
    weight:        '180 г',
    description_bg:'рибен хайвер, зехтин, лимон, хляб',
    description_en:'fish roe, olive oil, lemon, bread',
    allergens:     ['fish', 'gluten'],
    image:         'menu-images/Тарама.png',
  },
  {
    id:            'plato-razyadki',
    category:      'starters',
    name_bg:       'Плато разядки',
    name_en:       'Dips Platter',
    price:         25.10,
    price_unit:    null,
    weight:        '550 г',
    description_bg:'дзадзики, тирокафтери, тарама, маслини',
    description_en:'tzatziki, tirokafteri, tarama, olives',
    allergens:     ['milk', 'fish', 'gluten'],
    image:         'menu-images/Плато разядки.png',
  },
  {
    id:            'gratska-pitka',
    category:      'starters',
    name_bg:       'Гръцка питка',
    name_en:       'Greek Pita Bread',
    price:         1.70,
    price_unit:    null,
    weight:        '60 г',
    description_bg:'питка, зехтин, риган',
    description_en:'pita bread, olive oil, oregano',
    allergens:     ['gluten'],
    image:         'menu-images/Гръцка питка.png',
  },
  {
    id:            'paprika',
    category:      'starters',
    name_bg:       'Паприка',
    name_en:       'Paprika Chicken',
    price:         12.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'пиле, чушка, домати, боб, магданоз',
    description_en:'chicken, pepper, tomatoes, beans, parsley',
    allergens:     [],
    image:         'menu-images/Паприка.png',
  },
  {
    id:            'pikantno-feta-na-folio',
    category:      'starters',
    name_bg:       'Пикантно фета сирене, печено на фолио',
    name_en:       'Spicy Feta Baked in Foil',
    price:         12.80,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'сирене фета, домат, чушка',
    description_en:'feta cheese, tomato, pepper',
    allergens:     ['milk'],
    image:         'menu-images/Пикантно фета сирене печено на фолио.png',
  },

  // ── ПРЕДЯСТИЯ ─────────────────────────────────────────────────────────────

  {
    id:            'zelenchutsi-na-skara',
    category:      'appetizers',
    name_bg:       'Зеленчуци на скара',
    name_en:       'Grilled Vegetables',
    price:         12.30,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'тиквички, патладжан, морков, домат, гъби, чушка, лук',
    description_en:'zucchini, eggplant, carrot, tomato, mushrooms, pepper, onion',
    allergens:     [],
    image:         'menu-images/Зеленчуци на скара.png',
  },
  {
    id:            'parzheni-tikvichki-s-dzadziki',
    category:      'appetizers',
    name_bg:       'Пържени тиквички с дзадзики',
    name_en:       'Fried Zucchini with Tzatziki',
    price:         11.50,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'тиквички, брашно, дзадзики',
    description_en:'zucchini, flour, tzatziki',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Пържени тиквички с дзадзики.png',
  },
  {
    id:            'parzheni-kartofi',
    category:      'appetizers',
    name_bg:       'Пържени картофи',
    name_en:       'French Fries',
    price:         8.60,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'картофи',
    description_en:'potatoes',
    allergens:     [],
    image:         'menu-images/Пържени картофи.png',
  },
  {
    id:            'parzheni-kartofi-sas-sirene',
    category:      'appetizers',
    name_bg:       'Пържени картофи със сирене',
    name_en:       'Fries with Cheese',
    price:         9.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'картофи, настъргано сирене',
    description_en:'potatoes, grated cheese',
    allergens:     ['milk'],
    image:         'menu-images/Пържени картофи със сирене.png',
  },
  {
    id:            'kavarma-saganaki',
    category:      'appetizers',
    name_bg:       'Кавърма Саганаки',
    name_en:       'Kavarma Saganaki',
    price:         15.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'телешко месо, червена и зелена чушка, домат, пресен лук, гауда',
    description_en:'veal, red and green pepper, tomato, fresh onion, gouda cheese',
    allergens:     ['milk'],
    image:         'menu-images/Кавърма Саганаки.png',
  },
  {
    id:            'skaridi-saganaki',
    category:      'appetizers',
    name_bg:       'Скариди Саганаки',
    name_en:       'Shrimp Saganaki',
    price:         26.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'скариди, домати, сирене, риган, магданоз',
    description_en:'shrimp, tomatoes, cheese, oregano, parsley',
    allergens:     ['crustaceans', 'milk'],
    image:         'menu-images/Скариди Саганаки.png',
  },
  {
    id:            'palneni-gabi-s-bekon',
    category:      'appetizers',
    name_bg:       'Пълнени гъби с бекон, чушки, гауда',
    name_en:       'Stuffed Mushrooms with Bacon & Gouda',
    price:         12.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'гъби, бекон, чушки, сирене гауда, магданоз',
    description_en:'mushrooms, bacon, peppers, gouda cheese, parsley',
    allergens:     ['milk'],
    image:         'menu-images/Пълнени гъби с бекон чушки гауда.png',
  },
  {
    id:            'buyurdi-gyuvech',
    category:      'appetizers',
    name_bg:       'Буюрди /гювече',
    name_en:       'Bouyiourdi (Baked Cheese Gyuvech)',
    price:         15.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домат, червена и зелена чушка, сирене фета, гравиера, гауда, риган',
    description_en:'tomato, red and green pepper, feta cheese, graviera, gouda, oregano',
    allergens:     ['milk'],
    image:         'menu-images/Буюрди гювече.png',
  },
  {
    id:            'palnен-patladzhan',
    category:      'appetizers',
    name_bg:       'Пълнен патладжан',
    name_en:       'Stuffed Eggplant',
    price:         12.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'патладжан, домат, сирене фета, риган, чесън, магданоз',
    description_en:'eggplant, tomato, feta cheese, oregano, garlic, parsley',
    allergens:     ['milk'],
    image:         'menu-images/Пълнен патладжан.png',
  },
  {
    id:            'midi-saganaki',
    category:      'appetizers',
    name_bg:       'Миди Саганаки',
    name_en:       'Mussels Saganaki',
    price:         19.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'миди, домати, сирене, риган, магданоз',
    description_en:'mussels, tomatoes, cheese, oregano, parsley',
    allergens:     ['milk', 'molluscs'],
    image:         'menu-images/Миди Саганаки.png',
  },
  {
    id:            'kroketi-miks',
    category:      'appetizers',
    name_bg:       'Крокети микс',
    name_en:       'Croquettes Mix',
    price:         10.50,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'зеленчукови, със сирена и с месо',
    description_en:'vegetable, cheese, and meat croquettes',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Крокети микс.png',
  },
  {
    id:            'machkani-beybi-kartofi',
    category:      'appetizers',
    name_bg:       'Мачкани бейби картофи',
    name_en:       'Smashed Baby Potatoes',
    price:         9.00,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'бейби картофи, зехтин, чесън, паприка',
    description_en:'baby potatoes, olive oil, garlic, paprika',
    allergens:     [],
    image:         'menu-images/Мачкани бейби картофи.png',
  },
  {
    id:            'parzheni-chushki-i-patladzhan',
    category:      'appetizers',
    name_bg:       'Пържени чушки и патладжани',
    name_en:       'Fried Peppers & Eggplant',
    price:         11.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'чушки, патладжан, доматен сос',
    description_en:'peppers, eggplant, tomato sauce',
    allergens:     [],
    image:         'menu-images/Пържени чушки и патладжани.png',
  },
  // ── СПЕЦИАЛИТЕТИ ──────────────────────────────────────────────────────────

  {
    id:            'kralski-kotlet',
    category:      'specialties',
    name_bg:       'Кралски котлет',
    name_en:       "King's Pork Chop",
    price:         22.00,
    price_unit:    null,
    weight:        '450 г',
    description_bg:'котлет с ребро от свинско месо с гарнитура пържени картофи и дзадзики',
    description_en:'bone-in pork chop, served with fries and tzatziki',
    allergens:     ['milk'],
    image:         'menu-images/Кралски котлет.png',
  },

  {
    id:            'svinski-shnitsel-s-gabi',
    category:      'specialties',
    name_bg:       'Свински шницел с гъби и сметана',
    name_en:       'Pork Schnitzel with Mushrooms & Cream',
    price:         21.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свинско месо, гъби, сметана, пържени картофи',
    description_en:'pork, mushrooms, cream, fries',
    allergens:     ['milk'],
    image:         'menu-images/Свински шницел с гъби и сметана.png',
  },
  {
    id:            'svinski-bekon-grilovani-zelenchutsi',
    category:      'specialties',
    name_bg:       'Свински бекон на скара с гриловани зеленчуци',
    name_en:       'Grilled Pork Bacon with Grilled Vegetables',
    price:         19.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свински бекон, тиквички, патладжан, лук, дзадзики',
    description_en:'pork bacon, zucchini, eggplant, onion, tzatziki',
    allergens:     ['milk'],
    image:         'menu-images/Свински бекон на скара с гриловани зеленчуци.png',
  },
  {
    id:            'svinsko-bon-file-s-sos-ot-sirena',
    category:      'specialties',
    name_bg:       'Свинско бон филе със сос от сирена',
    name_en:       'Pork Fillet in Cheese Sauce',
    price:         21.10,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свинско бон филе, гъби, сметана, сирена',
    description_en:'pork fillet, mushrooms, cream, cheeses',
    allergens:     ['milk'],
    image:         'menu-images/Свинско бон филе със сос от сирена.png',
  },
  {
    id:            'kebap-s-kiselo-mlyako',
    category:      'specialties',
    name_bg:       'Кебап с кисело мляко и салса',
    name_en:       'Kebab with Yogurt & Salsa Sauce',
    price:         22.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'телешко и агнешко месо, кисело мляко, салса сос',
    description_en:'veal and lamb, yogurt, salsa sauce',
    allergens:     ['milk'],
    image:         'menu-images/Кебап с кисело мляко и салса.png',
  },
  {
    id:            'pileshki-shnitsel-s-gabi',
    category:      'specialties',
    name_bg:       'Пилешки шницел с гъби и сметана',
    name_en:       'Chicken Schnitzel with Mushrooms & Cream',
    price:         20.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'пилешко месо, гъби, сметана, картофи',
    description_en:'chicken, mushrooms, cream, potatoes',
    allergens:     ['milk'],
    image:         'menu-images/Пилешки шницел с гъби и сметана.png',
  },
  {
    id:            'teleshko-bon-file',
    category:      'specialties',
    name_bg:       'Телешко бон филе',
    name_en:       'Veal Fillet',
    price:         22.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешко месо, бейби картофи, пепър сос',
    description_en:'veal, baby potatoes, pepper sauce',
    allergens:     [],
    image:         'menu-images/Телешко бон филе.png',
  },

  // ── МЕСНИ ЯСТИЯ ───────────────────────────────────────────────────────────

  {
    id:            'suvlaki-pileshko',
    category:      'bbq-meat',
    name_bg:       'Сувлаки пилешко порция',
    name_en:       'Chicken Souvlaki',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'пилешко месо, пържени картофи, дзадзики, лимон',
    description_en:'chicken, fries, tzatziki, lemon',
    allergens:     ['milk'],
    image:         'menu-images/Сувлаки пилешко порция.png',
  },
  {
    id:            'suvlaki-svinsko',
    category:      'bbq-meat',
    name_bg:       'Сувлаки свинско порция',
    name_en:       'Pork Souvlaki',
    price:         18.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'свинско месо, пържени картофи, дзадзики, лимон',
    description_en:'pork, fries, tzatziki, lemon',
    allergens:     ['milk'],
    image:         'menu-images/Сувлаки свинско порция.png',
  },
  {
    id:            'pileshko-file-na-skara',
    category:      'bbq-meat',
    name_bg:       'Пилешко филе на скара',
    name_en:       'Grilled Chicken Fillet',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'пилешко филе, пържени картофи, дзадзики, лимон',
    description_en:'chicken fillet, fries, tzatziki, lemon',
    allergens:     ['milk'],
    image:         'menu-images/Пилешко филе на скара.png',
  },
  {
    id:            'palnен-biftek-graviera',
    category:      'bbq-meat',
    name_bg:       'Пълнен бифтек със сирене гравиера',
    name_en:       'Stuffed Beef Patty with Graviera Cheese',
    price:         20.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешка кайма, сирене гравиера, пържени картофи, дзадзики',
    description_en:'veal mince, graviera cheese, fries, tzatziki',
    allergens:     ['milk'],
    image:         'menu-images/Пълнен бифтек със сирене гравиера.png',
  },
  {
    id:            'biftek',
    category:      'bbq-meat',
    name_bg:       'Бифтек',
    name_en:       'Beef Patty',
    price:         18.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешка кайма, пържени картофи, дзадзики',
    description_en:'veal mince, fries, tzatziki',
    allergens:     ['milk'],
    image:         'menu-images/Бифтек.png',
  },

  {
    id:            'daska-s-mesa-za-dvama',
    category:      'bbq-meat',
    name_bg:       'Дъска с меса за двама',
    name_en:       'Meat Board for Two',
    price:         39.00,
    price_unit:    null,
    weight:        '1000 г',
    description_bg:'пилешко филе, свинско шишче, пилешко шишче, бифтек, селска наденица',
    description_en:'chicken fillet, pork skewer, chicken skewer, beef patty, village sausage',
    allergens:     [],
    image:         'menu-images/Дъска с меса за двама.png',
  },
  {
    id:            'svinska-vratna-parzhola',
    category:      'bbq-meat',
    name_bg:       'Свинска вратна пържола',
    name_en:       'Pork Neck Steak',
    price:         17.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свинска вратна пържола, пържени картофи, дзадзики',
    description_en:'pork neck steak, fries, tzatziki',
    allergens:     ['milk'],
    image:         'menu-images/Свинска вратна пържола.png',
  },
  {
    id:            'suvlaki-miks',
    category:      'bbq-meat',
    name_bg:       'Сувлаки микс',
    name_en:       'Souvlaki Mix',
    price:         19.90,
    price_unit:    null,
    weight:        '450 г',
    description_bg:'свинско месо, пилешко месо, питка, дзадзики, магданоз',
    description_en:'pork, chicken, pita bread, tzatziki, parsley',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Сувлаки пилешко порция.png',
  },
  {
    id:            'suvlaki-teleshko',
    category:      'bbq-meat',
    name_bg:       'Телешко сувлаки',
    name_en:       'Veal Souvlaki',
    price:         21.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'телешко месо, питка, сирене фета, чушки, маслини',
    description_en:'veal, pita bread, feta cheese, peppers, olives',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Телешко сувлаки.png',
  },
  {
    id:            'selska-nadenitsa',
    category:      'bbq-meat',
    name_bg:       'Селска наденица',
    name_en:       'Village Sausage',
    price:         17.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'наденица, чери домати, мащерка, дзадзики',
    description_en:'sausage, cherry tomatoes, thyme, tzatziki',
    allergens:     ['milk'],
    image:         'menu-images/Селска наденица.png',
  },
  {
    id:            'teleshka-parzhola',
    category:      'bbq-meat',
    name_bg:       'Телешка пържола',
    name_en:       'Veal Steak',
    price:         19.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешко месо, масло, розмарин',
    description_en:'veal, butter, rosemary',
    allergens:     ['milk'],
    image:         'menu-images/Телешка пържола.png',
  },
  {
    id:            'agneshki-rebra',
    category:      'bbq-meat',
    name_bg:       'Агнешки ребра',
    name_en:       'Lamb Ribs',
    price:         19.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'агнешки ребра, мед, сусам, чери домати',
    description_en:'lamb ribs, honey, sesame, cherry tomatoes',
    allergens:     ['sesame'],
    image:         'menu-images/Агнешки ребра.png',
  },
  {
    id:            'agneshki-kebap',
    category:      'bbq-meat',
    name_bg:       'Кебап телешко и агнешко',
    name_en:       'Veal & Lamb Kebab',
    price:         19.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'телешка и агнешка кайма, лук, подправки',
    description_en:'veal and lamb mince, onion, spices',
    allergens:     [],
    image:         'menu-images/Кебап телешко и агнешко.png',
  },

  // ── НА ТИГАН ──────────────────────────────────────────────────────────────

  {
    id:            'pileshki-kystcheta-rozmarin',
    category:      'pan-meat',
    name_bg:       'Пилешки късчета с розмарин, гъби и горчица',
    name_en:       'Chicken Pieces with Rosemary, Mushrooms & Mustard',
    price:         17.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'пилешко месо, гъби, горчица, сметана, розмарин',
    description_en:'chicken, mushrooms, mustard, cream, rosemary',
    allergens:     ['milk', 'mustard'],
    image:         'menu-images/Пилешки късчета с розмарин гъби и горчица.png',
  },
  {
    id:            'svinski-kystcheta-chushki',
    category:      'pan-meat',
    name_bg:       'Свински късчета с чушки и мащерка',
    name_en:       'Pork Pieces with Peppers & Thyme',
    price:         18.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'свинско месо, чушки, мащерка, лимон',
    description_en:'pork, peppers, thyme, lemon',
    allergens:     [],
    image:         'menu-images/Свински късчета с чушки и мащерка.png',
  },
  {
    id:            'teleshki-drob-karameliziran-luk',
    category:      'pan-meat',
    name_bg:       'Телешки дроб с карамелизиран лук',
    name_en:       'Veal Liver with Caramelized Onion',
    price:         16.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешки дроб, карамелизиран лук, гъби, лимон',
    description_en:'veal liver, caramelized onion, mushrooms, lemon',
    allergens:     [],
    image:         'menu-images/Телешки дроб с карамелизиран лук.png',
  },

  // ── ПАСТА И РИЗОТО ────────────────────────────────────────────────────────

  {
    id:            'papadele-sas-somga',
    category:      'pasta',
    name_bg:       'Папарделе със сьомга',
    name_en:       'Pappardelle with Salmon',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'сметана, чери домати, пушена сьомга, пармезан, мак',
    description_en:'cream, cherry tomatoes, smoked salmon, parmesan, poppy seed',
    allergens:     ['gluten', 'fish', 'milk'],
    image:         'menu-images/Папарделе със сьомга.png',
  },
  {
    id:            'papadele-s-teleshko',
    category:      'pasta',
    name_bg:       'Папарделе с телешко',
    name_en:       'Pappardelle with Veal',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'папарделе, телешко месо, доматен сос, пармезан, магданоз',
    description_en:'pappardelle, veal, tomato sauce, parmesan, parsley',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Папарделе с телешко.png',
  },
  {
    id:            'lingvini-salsa-sos',
    category:      'pasta',
    name_bg:       'Лингуини със салса сос',
    name_en:       'Linguine in Salsa Sauce',
    price:         13.90,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'домати, пармезан',
    description_en:'tomatoes, parmesan',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Лингуини със салса сос.png',
  },
  {
    id:            'rizoto-s-pileshko-i-zelenchutsi',
    category:      'pasta',
    name_bg:       'Ризото с пилешко и зеленчуци',
    name_en:       'Risotto with Chicken & Vegetables',
    price:         16.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'ориз, пилешко месо, гъби, чушки, пармезан',
    description_en:'rice, chicken, mushrooms, peppers, parmesan',
    allergens:     ['milk'],
    image:         'menu-images/Ризото с пилешко и зеленчуци.png',
  },
  {
    id:            'rizoto-s-morski-darove',
    category:      'pasta',
    name_bg:       'Ризото с морски дарове',
    name_en:       'Seafood Risotto',
    price:         28.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'ориз, скариди, миди, калмари, зехтин',
    description_en:'rice, shrimp, mussels, calamari, olive oil',
    allergens:     ['crustaceans', 'molluscs'],
    image:         'menu-images/Ризото с морски дарове.png',
  },
  {
    id:            'kritaroto-s-morski-darove',
    category:      'pasta',
    name_bg:       'Критарото с морски дарове',
    name_en:       'Seafood Kritharoto',
    price:         28.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'скариди, миди, калмари, салца сос, босилек',
    description_en:'shrimp, mussels, calamari, salsa sauce, basil',
    allergens:     ['gluten', 'crustaceans', 'molluscs'],
    image:         'menu-images/Критарото с морски дарове.png',
  },
  {
    id:            'pasta-sas-skaridi',
    category:      'pasta',
    name_bg:       'Паста със скариди',
    name_en:       'Pasta with Shrimp',
    price:         27.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'скариди, чери домати, салца сос, босилек',
    description_en:'shrimp, cherry tomatoes, salsa sauce, basil',
    allergens:     ['gluten', 'crustaceans'],
    image:         'menu-images/Паста със скариди.png',
  },
  {
    id:            'pene-s-pileshko-i-smetana',
    category:      'pasta',
    name_bg:       'Пене с пилешко и сметана',
    name_en:       'Penne with Chicken & Cream Sauce',
    price:         16.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'чушки, гъби, сметанов сос, естрагон',
    description_en:'peppers, mushrooms, cream sauce, tarragon',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Пене с пилешко и сметана.png',
  },
  {
    id:            'taliateli-pileshko-dizhon',
    category:      'pasta',
    name_bg:       'Талиатели с пилешко филе и сос \'Дижон\'',
    name_en:       'Tagliatelle with Chicken Fillet in Dijon Sauce',
    price:         19.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'талиатели, пилешко филе, сос Дижон, сметана',
    description_en:'tagliatelle, chicken fillet, Dijon sauce, cream',
    allergens:     ['gluten', 'milk', 'mustard'],
    image:         'menu-images/Талиатели с пилешко филе и сос Дижон.png',
  },

  // ── РИБИ ──────────────────────────────────────────────────────────────────

  {
    id:            'gavros-na-tigan',
    category:      'fish',
    name_bg:       'Гаврос на тиган',
    name_en:       'Pan-Fried Anchovy',
    price:         15.00,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'гаврос, брашно, лимон, магданоз',
    description_en:'anchovy, flour, lemon, parsley',
    allergens:     ['fish', 'gluten'],
    image:         'menu-images/Гаврос на тиган.png',
  },
  {
    id:            'kalmari-na-tigan',
    category:      'fish',
    name_bg:       'Калмари на тиган',
    name_en:       'Pan-Fried Calamari',
    price:         22.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'калмари, брашно, лимон, дзадзики',
    description_en:'calamari, flour, lemon, tzatziki',
    allergens:     ['gluten', 'milk', 'molluscs'],
    image:         'menu-images/Калмари на тиган.png',
  },
  {
    id:            'palnен-kalmar',
    category:      'fish',
    name_bg:       'Пълнен калмар',
    name_en:       'Stuffed Calamari',
    price:         24.60,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домати, сирене фета, гауда, каперси',
    description_en:'tomatoes, feta cheese, gouda, capers',
    allergens:     ['milk', 'molluscs'],
    image:         'menu-images/Пълнен калмар.png',
  },
  {
    id:            'oktopod-na-skara',
    category:      'fish',
    name_bg:       'Октопод на скара',
    name_en:       'Grilled Octopus',
    price:         29.00,
    price_unit:    null,
    weight:        '150 г',
    description_bg:'октопод, зехтин, чесън, лимон',
    description_en:'octopus, olive oil, garlic, lemon',
    allergens:     ['molluscs'],
    image:         'menu-images/Октопод на скара.png',
  },
  {
    id:            'skaridi-na-skara',
    category:      'fish',
    name_bg:       'Скариди на скара',
    name_en:       'Grilled Shrimp',
    price:         24.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'скариди, зехтин, чери домати, магданоз, лимон',
    description_en:'shrimp, olive oil, cherry tomatoes, parsley, lemon',
    allergens:     ['crustaceans'],
    image:         'menu-images/Скариди на скара.png',
  },
  {
    id:            'pushena-skumriya',
    category:      'fish',
    name_bg:       'Пушена скумрия',
    name_en:       'Smoked Mackerel',
    price:         15.00,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'пушена скумрия, лук, лимон, магданоз',
    description_en:'smoked mackerel, onion, lemon, parsley',
    allergens:     ['fish'],
    image:         'menu-images/Пушена скумрия.png',
  },
  {
    id:            'marinovan-gavros',
    category:      'fish',
    name_bg:       'Маринован гаврос',
    name_en:       'Marinated Anchovy',
    price:         15.00,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'гаврос, зехтин, лук, лимон, магданоз',
    description_en:'anchovy, olive oil, onion, lemon, parsley',
    allergens:     ['fish'],
    image:         'menu-images/Маринован гаврос.png',
  },
  {
    id:            'skaridi-na-tigan',
    category:      'fish',
    name_bg:       'Скариди на тиган',
    name_en:       'Pan-Fried Shrimp',
    price:         24.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'скариди, зехтин, чери домати, лимон, магданоз',
    description_en:'shrimp, olive oil, cherry tomatoes, lemon, parsley',
    allergens:     ['crustaceans'],
    image:         'menu-images/Скариди на тиган.png',
  },
  {
    id:            'kalmar-na-plocha',
    category:      'fish',
    name_bg:       'Калмар на плоча',
    name_en:       'Plancha-Grilled Calamari',
    price:         22.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'калмар, зехтин, лимон, дзадзики',
    description_en:'calamari, olive oil, lemon, tzatziki',
    allergens:     ['milk', 'molluscs'],
    image:         'menu-images/Калмар на плоча.png',
  },
  {
    id:            'plato-s-morski-darove',
    category:      'fish',
    name_bg:       'Плато с морски дарове',
    name_en:       'Seafood Platter',
    price:         68.90,
    price_unit:    null,
    weight:        '600 г',
    description_bg:'гаврос, калмар, скариди, миди, октопод',
    description_en:'anchovy, calamari, shrimp, mussels, octopus',
    allergens:     ['fish', 'crustaceans', 'molluscs'],
    image:         'menu-images/plato-morski-darove.png',
  },
  {
    id:            'barbun',
    category:      'fish',
    name_bg:       'Барбун',
    name_en:       'Red Mullet',
    price:         32.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'барбун, зехтин, лимон, чесън, магданоз',
    description_en:'red mullet, olive oil, lemon, garlic, parsley',
    allergens:     ['fish'],
    image:         'menu-images/barbun.png',
  },
  {
    id:            'lavrak-na-skara',
    category:      'fish',
    name_bg:       'Лаврак на скара',
    name_en:       'Grilled Sea Bass',
    price:         8.00,
    price_unit:    '100 г',
    weight:        '400 г',
    description_bg:'лаврак, картофи, спанак, чери домати, зехтин, лимон',
    description_en:'sea bass, potatoes, spinach, cherry tomatoes, olive oil, lemon',
    allergens:     ['fish'],
    image:         'menu-images/Лаврак на скара.png',
  },
  {
    id:            'chipura',
    category:      'fish',
    name_bg:       'Ципура',
    name_en:       'Sea Bream',
    price:         8.00,
    price_unit:    '100 г',
    weight:        '450 г',
    description_bg:'ципура, рукола, червена чушка, лимон, зехтин',
    description_en:'sea bream, arugula, red pepper, lemon, olive oil',
    allergens:     ['fish'],
    image:         'menu-images/Лаврак на скара.png',
  },
  {
    id:            'somga-na-skara',
    category:      'fish',
    name_bg:       'Сьомга на скара',
    name_en:       'Grilled Salmon',
    price:         28.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'сьомга, зехтин, лимон, розмарин',
    description_en:'salmon, olive oil, lemon, rosemary',
    allergens:     ['fish'],
    image:         'menu-images/Сьомга на скара.png',
  },
  {
    id:            'gavros-na-skara',
    category:      'fish',
    name_bg:       'Гаврос на скара',
    name_en:       'Grilled Anchovy',
    price:         12.90,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'гаврос, брашно, лимон, рукола, магданоз',
    description_en:'anchovy, flour, lemon, arugula, parsley',
    allergens:     ['fish', 'gluten'],
    image:         'menu-images/Гаврос на скара.png',
  },
  {
    id:            'pastarva-na-tigan',
    category:      'fish',
    name_bg:       'Пъстърва на тиган',
    name_en:       'Pan-Fried Trout',
    price:         22.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'пъстърва, зехтин, лимон, розмарин, домати',
    description_en:'trout, olive oil, lemon, rosemary, tomatoes',
    allergens:     ['fish'],
    image:         'menu-images/Пъстърва на тиган.png',
  },
  {
    id:            'zadusheni-midi',
    category:      'fish',
    name_bg:       'Задушени миди',
    name_en:       'Steamed Mussels',
    price:         16.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'миди, зехтин, лимон, чушки, магданоз',
    description_en:'mussels, olive oil, lemon, peppers, parsley',
    allergens:     ['molluscs'],
    image:         'menu-images/Задушени миди.png',
  },

];
