// Menu data — Tavernaki restaurant
// 8 categories, 71 dishes
// Prices in лв (BGN). Descriptions in Bulgarian, exactly as provided.
window.menuData = [

  // ── САЛАТИ ────────────────────────────────────────────────────────────────

  {
    id:            'selska-salata',
    category:      'salads',
    name_bg:       'Селска салата',
    name_en:       'Селска салата',
    price:         11.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'домат, краставица, чушка, лук, маслини, сирене фета, магданоз, риган, каперси',
    allergens:     ['milk'],
    image:         'menu-images/Селска Салата.png',
  },
  {
    id:            'salata-zele-s-morkovi',
    category:      'salads',
    name_bg:       'Салата зеле с моркови',
    name_en:       'Салата зеле с моркови',
    price:         8.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'зеле, моркови, целина, чушка, дресинг',
    allergens:     ['celery'],
    image:         'menu-images/Салата зеле с моркови.png',
  },
  {
    id:            'salata-dakos-krit',
    category:      'salads',
    name_bg:       'Салата Дакос крит',
    name_en:       'Салата Дакос крит',
    price:         11.40,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'хлебче дакос, домат, натрошено сирене фета, маслини, риган',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Салата Дакос крит.png',
  },
  {
    id:            'zelena-salata',
    category:      'salads',
    name_bg:       'Зелена салата',
    name_en:       'Зелена салата',
    price:         12.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'марули, чери домат, сушени смокини, кедрови ядки, сирене манури, балсамов дресинг',
    allergens:     ['milk', 'nuts'],
    image:         'menu-images/Зелена салата.png',
  },
  {
    id:            'salata-roka-s-halumi',
    category:      'salads',
    name_bg:       'Салата Рока с халуми',
    name_en:       'Салата Рока с халуми',
    price:         14.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'марули, рукола, червено цвекло, сушени домати, катък, ябълка, гриловано халуми, орехи, цитрусов дресинг',
    allergens:     ['milk', 'nuts'],
    image:         'menu-images/Салата Рока с халуми.png',
  },
  {
    id:            'salata-tsezar',
    category:      'salads',
    name_bg:       'Салата Цезар',
    name_en:       'Салата Цезар',
    price:         14.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'айсберг, крутони, бекон, пилешко филе, чери домат, пармезан, сос цезар',
    allergens:     ['gluten', 'milk', 'fish'],
    image:         'menu-images/Салата Цезар.png',
  },
  {
    id:            'salata-greko-kapreze',
    category:      'salads',
    name_bg:       'Салата Греко капрезе',
    name_en:       'Салата Греко капрезе',
    price:         12.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домат, моцарела, рукола, босилеков дресинг',
    allergens:     ['milk'],
    image:         'menu-images/Салата Греко капрезе.png',
  },
  {
    id:            'salata-s-morski-darove',
    category:      'salads',
    name_bg:       'Салата с морски дарове',
    name_en:       'Салата с морски дарове',
    price:         23.90,
    price_unit:    null,
    weight:        '450 г',
    description_bg:'марули, айсберг, чери домати, пармезан, скариди, калмари, балсамов дресинг',
    allergens:     ['milk', 'crustaceans', 'molluscs'],
    image:         'menu-images/Салата с морски дар.png',
  },
  {
    id:            'salata-s-pecheni-chushki',
    category:      'salads',
    name_bg:       'Салата с печени чушки',
    name_en:       'Салата с печени чушки',
    price:         12.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домати, печени чушки, сирене фета, червен лук, риган, дресинг',
    allergens:     ['milk'],
    image:         'menu-images/Салата с печени чушки.png',
  },
  {
    id:            'kinoa-i-skaridi',
    category:      'salads',
    name_bg:       'Киноа и скариди',
    name_en:       'Киноа и скариди',
    price:         18.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'киноа, скариди, чери домати, моркови, авокадо, крутони, дресинг',
    allergens:     ['gluten', 'crustaceans'],
    image:         'menu-images/Киноа и скариди.png',
  },
  {
    id:            'redena-salata',
    category:      'salads',
    name_bg:       'Редена салата',
    name_en:       'Редена салата',
    price:         16.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домати, лук, сирене, челена и червена чушка, краставици, маслини, плочка сирене',
    allergens:     ['milk'],
    image:         'menu-images/Редена салата.png',
  },
  {
    id:            'salata-sas-spanak',
    category:      'salads',
    name_bg:       'Салата със спанак',
    name_en:       'Салата със спанак',
    price:         12.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'спанак, натрошено сирене фета, пресен лук, копър, медени корички',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Салата със спанак.png',
  },

  // ── СТАРТЕРИ ──────────────────────────────────────────────────────────────

  {
    id:            'feta-v-hrupkava-korichka',
    category:      'starters',
    name_bg:       'Фета сирене обвито в хрупкава коричка с орехи и мед',
    name_en:       'Фета сирене обвито в хрупкава коричка с орехи и мед',
    price:         12.80,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'сирене фета, тестена обвивка, мед, сусам, орехи',
    allergens:     ['gluten', 'milk', 'sesame', 'nuts'],
    image:         'menu-images/Фета сирене обвито в хрупкава коричка с орехи и мед.png',
  },
  {
    id:            'feta-s-zehtin-i-rigan',
    category:      'starters',
    name_bg:       'Фета сирене със зехтин и риган',
    name_en:       'Фета сирене със зехтин и риган',
    price:         7.90,
    price_unit:    null,
    weight:        '100 г',
    description_bg:'сирене фета, зехтин, риган',
    allergens:     ['milk'],
    image:         'menu-images/Фета сирене със зехтин и риган.png',
  },
  {
    id:            'grilovano-halumi',
    category:      'starters',
    name_bg:       'Гриловано Халуми',
    name_en:       'Гриловано Халуми',
    price:         10.90,
    price_unit:    null,
    weight:        '150 г',
    description_bg:'сирене халуми, балсамов дресинг, чери домати',
    allergens:     ['milk'],
    image:         'menu-images/Гриловано Халуми.png',
  },
  {
    id:            'lyuti-chushki',
    category:      'starters',
    name_bg:       'Люти чушки',
    name_en:       'Люти чушки',
    price:         5.50,
    price_unit:    null,
    weight:        '100 г',
    description_bg:'люти чушки, зехтин, оцет, магданоз',
    allergens:     [],
    image:         'menu-images/Люти чушки.png',
  },
  {
    id:            'dzadziki',
    category:      'starters',
    name_bg:       'Дзадзики',
    name_en:       'Дзадзики',
    price:         8.60,
    price_unit:    null,
    weight:        '180 г',
    description_bg:'кисело мляко, краставица, чесън, копър, зехтин',
    allergens:     ['milk'],
    image:         'menu-images/Дзадзики.png',
  },
  {
    id:            'tirokafteri',
    category:      'starters',
    name_bg:       'Тирокафтери',
    name_en:       'Тирокафтери',
    price:         8.60,
    price_unit:    null,
    weight:        '180 г',
    description_bg:'сирене фета, люта чушка, зехтин',
    allergens:     ['milk'],
    image:         'menu-images/Тирокафтери.png',
  },
  {
    id:            'tarama',
    category:      'starters',
    name_bg:       'Тарама',
    name_en:       'Тарама',
    price:         8.60,
    price_unit:    null,
    weight:        '180 г',
    description_bg:'рибен хайвер, зехтин, лимон, хляб',
    allergens:     ['fish', 'gluten'],
    image:         'menu-images/Тарама.png',
  },
  {
    id:            'plato-razyadki',
    category:      'starters',
    name_bg:       'Плато разядки',
    name_en:       'Плато разядки',
    price:         25.10,
    price_unit:    null,
    weight:        '550 г',
    description_bg:'дзадзики, тирокафтери, тарама, маслини',
    allergens:     ['milk', 'fish', 'gluten'],
    image:         'menu-images/Плато разядки.png',
  },
  {
    id:            'gratska-pitka',
    category:      'starters',
    name_bg:       'Гръцка питка',
    name_en:       'Гръцка питка',
    price:         1.70,
    price_unit:    null,
    weight:        '60 г',
    description_bg:'питка, зехтин, риган',
    allergens:     ['gluten'],
    image:         'menu-images/Гръцка питка.png',
  },
  {
    id:            'tarator',
    category:      'starters',
    name_bg:       'Таратор',
    name_en:       'Таратор',
    price:         8.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'кисело мляко, краставица, копър, чесън',
    allergens:     ['milk'],
    image:         'menu-images/Таратор.png',
  },
  {
    id:            'paprika',
    category:      'starters',
    name_bg:       'Паприка',
    name_en:       'Паприка',
    price:         12.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'пиле, чушка, домати, боб, магданоз',
    allergens:     [],
    image:         'menu-images/Паприка.png',
  },
  {
    id:            'pikantno-feta-na-folio',
    category:      'starters',
    name_bg:       'Пикантно фета сирене, печено на фолио',
    name_en:       'Пикантно фета сирене, печено на фолио',
    price:         12.80,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'сирене фета, домат, чушка',
    allergens:     ['milk'],
    image:         'menu-images/Пикантно фета сирене печено на фолио.png',
  },

  // ── ПРЕДЯСТИЯ ─────────────────────────────────────────────────────────────

  {
    id:            'zelenchutsi-na-skara',
    category:      'appetizers',
    name_bg:       'Зеленчуци на скара',
    name_en:       'Зеленчуци на скара',
    price:         12.30,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'тиквички, патладжан, морков, домат, гъби, чушка, лук',
    allergens:     [],
    image:         'menu-images/Зеленчуци на скара.png',
  },
  {
    id:            'parzheni-tikvichki-s-dzadziki',
    category:      'appetizers',
    name_bg:       'Пържени тиквички с дзадзики',
    name_en:       'Пържени тиквички с дзадзики',
    price:         11.50,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'тиквички, брашно, дзадзики',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Пържени тиквички с дзадзики.png',
  },
  {
    id:            'parzheni-kartofi',
    category:      'appetizers',
    name_bg:       'Пържени картофи',
    name_en:       'Пържени картофи',
    price:         8.60,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'картофи',
    allergens:     [],
    image:         'menu-images/Пържени картофи.png',
  },
  {
    id:            'parzheni-kartofi-sas-sirene',
    category:      'appetizers',
    name_bg:       'Пържени картофи със сирене',
    name_en:       'Пържени картофи със сирене',
    price:         9.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'картофи, настъргано сирене',
    allergens:     ['milk'],
    image:         'menu-images/Пържени картофи със сирене.png',
  },
  {
    id:            'kavarma-saganaki',
    category:      'appetizers',
    name_bg:       'Кавърма Саганаки',
    name_en:       'Кавърма Саганаки',
    price:         15.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'телешко месо, червена и зелена чушка, домат, пресен лук, гауда',
    allergens:     ['milk'],
    image:         'menu-images/Кавърма Саганаки.png',
  },
  {
    id:            'skaridi-saganaki',
    category:      'appetizers',
    name_bg:       'Скариди Саганаки',
    name_en:       'Скариди Саганаки',
    price:         26.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'скариди, домати, сирене, риган, магданоз',
    allergens:     ['crustaceans', 'milk'],
    image:         'menu-images/Скариди Саганаки.png',
  },
  {
    id:            'palneni-gabi-s-bekon',
    category:      'appetizers',
    name_bg:       'Пълнени гъби с бекон, чушки, гауда',
    name_en:       'Пълнени гъби с бекон, чушки, гауда',
    price:         12.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'гъби, бекон, чушки, сирене гауда, магданоз',
    allergens:     ['milk'],
    image:         'menu-images/Пълнени гъби с бекон чушки гауда.png',
  },
  {
    id:            'buyurdi-gyuvech',
    category:      'appetizers',
    name_bg:       'Буюрди /гювече',
    name_en:       'Буюрди /гювече',
    price:         15.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домат, червена и зелена чушка, сирене фета, гравиера, гауда, риган',
    allergens:     ['milk'],
    image:         'menu-images/Буюрди гювече.png',
  },
  {
    id:            'palnен-patladzhan',
    category:      'appetizers',
    name_bg:       'Пълнен патладжан',
    name_en:       'Пълнен патладжан',
    price:         12.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'патладжан, домат, сирене фета, риган, чесън, магданоз',
    allergens:     ['milk'],
    image:         'menu-images/Пълнен патладжан.png',
  },
  {
    id:            'midi-saganaki',
    category:      'appetizers',
    name_bg:       'Миди Саганаки',
    name_en:       'Миди Саганаки',
    price:         19.50,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'миди, домати, сирене, риган, магданоз',
    allergens:     ['milk', 'molluscs'],
    image:         'menu-images/Миди Саганаки.png',
  },
  {
    id:            'kroketi-miks',
    category:      'appetizers',
    name_bg:       'Крокети микс',
    name_en:       'Крокети микс',
    price:         10.50,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'зеленчукови, със сирена и с месо',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Крокети микс.png',
  },
  {
    id:            'machkani-beybi-kartofi',
    category:      'appetizers',
    name_bg:       'Мачкани бейби картофи',
    name_en:       'Мачкани бейби картофи',
    price:         9.00,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'бейби картофи, зехтин, чесън, паприка',
    allergens:     [],
    image:         'menu-images/Мачкани бейби картофи.png',
  },
  {
    id:            'parzheni-chushki-i-domati',
    category:      'appetizers',
    name_bg:       'Пържени чушки и домати',
    name_en:       'Пържени чушки и домати',
    price:         11.90,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'чушки, домати, домашен сос, сирене фета',
    allergens:     ['milk'],
    image:         'menu-images/Пържени чушки и домати.png',
  },
  {
    id:            'parzheni-chushki-i-patladzhan',
    category:      'appetizers',
    name_bg:       'Пържени чушки и патладжани',
    name_en:       'Пържени чушки и патладжани',
    price:         11.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'чушки, патладжан, доматен сос',
    allergens:     [],
    image:         'menu-images/Пържени чушки и патладжани.png',
  },
  {
    id:            'pechen-patladzhan',
    category:      'appetizers',
    name_bg:       'Печен патладжан',
    name_en:       'Печен патладжан',
    price:         9.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'патладжан, зехтин, чесън, босилек',
    allergens:     [],
    image:         'menu-images/Печен патладжан.png',
  },

  // ── СПЕЦИАЛИТЕТИ ──────────────────────────────────────────────────────────

  {
    id:            'kralski-kotlet',
    category:      'specialties',
    name_bg:       'Кралски котлет',
    name_en:       'Кралски котлет',
    price:         22.00,
    price_unit:    null,
    weight:        '450 г',
    description_bg:'котлет с ребро от свинско месо с гарнитура пържени картофи и дзадзики',
    allergens:     ['milk'],
    image:         'menu-images/Кралски котлет.png',
  },

  {
    id:            'svinski-shnitsel-s-gabi',
    category:      'specialties',
    name_bg:       'Свински шницел с гъби и сметана',
    name_en:       'Свински шницел с гъби и сметана',
    price:         21.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свинско месо, гъби, сметана, пържени картофи',
    allergens:     ['milk'],
    image:         'menu-images/Свински шницел с гъби и сметана.png',
  },
  {
    id:            'svinski-bekon-grilovani-zelenchutsi',
    category:      'specialties',
    name_bg:       'Свински бекон на скара с гриловани зеленчуци',
    name_en:       'Свински бекон на скара с гриловани зеленчуци',
    price:         19.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свински бекон, тиквички, патладжан, лук, дзадзики',
    allergens:     ['milk'],
    image:         'menu-images/Свински бекон на скара с гриловани зеленчуци.png',
  },
  {
    id:            'svinsko-bon-file-s-sos-ot-sirena',
    category:      'specialties',
    name_bg:       'Свинско бон филе със сос от сирена',
    name_en:       'Свинско бон филе със сос от сирена',
    price:         21.10,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свинско бон филе, гъби, сметана, сирена',
    allergens:     ['milk'],
    image:         'menu-images/Свинско бон филе със сос от сирена2.png',
  },
  {
    id:            'kebap-s-kiselo-mlyako',
    category:      'specialties',
    name_bg:       'Кебап с кисело мляко и салса',
    name_en:       'Кебап с кисело мляко и салса',
    price:         22.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'телешко и агнешко месо, кисело мляко, салса сос',
    allergens:     ['milk'],
    image:         'menu-images/Кебап с кисело мляко и салса.png',
  },
  {
    id:            'pileshki-shnitsel-s-gabi',
    category:      'specialties',
    name_bg:       'Пилешки шницел с гъби и сметана',
    name_en:       'Пилешки шницел с гъби и сметана',
    price:         20.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'пилешко месо, гъби, сметана, картофи',
    allergens:     ['milk'],
    image:         'menu-images/Пилешки шницел с гъби и сметана.png',
  },
  {
    id:            'teleshko-bon-file',
    category:      'specialties',
    name_bg:       'Телешко бон филе',
    name_en:       'Телешко бон филе',
    price:         22.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешко месо, розмарин, червени боровинки',
    allergens:     [],
    image:         'menu-images/Телешко бон филе.png',
  },

  // ── МЕСНИ ЯСТИЯ ───────────────────────────────────────────────────────────

  {
    id:            'suvlaki-pileshko',
    category:      'bbq-meat',
    name_bg:       'Сувлаки пилешко порция',
    name_en:       'Сувлаки пилешко порция',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'пилешко месо, пържени картофи, дзадзики, лимон',
    allergens:     ['milk'],
    image:         'menu-images/Сувлаки пилешко порция.png',
  },
  {
    id:            'suvlaki-svinsko',
    category:      'bbq-meat',
    name_bg:       'Сувлаки свинско порция',
    name_en:       'Сувлаки свинско порция',
    price:         18.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'свинско месо, пържени картофи, дзадзики, лимон',
    allergens:     ['milk'],
    image:         'menu-images/Сувлаки свинско порция.png',
  },
  {
    id:            'pileshko-file-na-skara',
    category:      'bbq-meat',
    name_bg:       'Пилешко филе на скара',
    name_en:       'Пилешко филе на скара',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'пилешко филе, пържени картофи, дзадзики, лимон',
    allergens:     ['milk'],
    image:         'menu-images/Пилешко филе на скара.png',
  },
  {
    id:            'palnен-biftek-graviera',
    category:      'bbq-meat',
    name_bg:       'Пълнен бифтек със сирене гравиера',
    name_en:       'Пълнен бифтек със сирене гравиера',
    price:         20.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешка кайма, сирене гравиера, пържени картофи, дзадзики',
    allergens:     ['milk'],
    image:         'menu-images/Пълнен бифтек със сирене гравиера.png',
  },
  {
    id:            'biftek',
    category:      'bbq-meat',
    name_bg:       'Бифтек',
    name_en:       'Бифтек',
    price:         18.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешка кайма, пържени картофи, дзадзики',
    allergens:     ['milk'],
    image:         'menu-images/Бифтек.png',
  },

  {
    id:            'daska-s-mesa-za-dvama',
    category:      'bbq-meat',
    name_bg:       'Дъска с меса за двама',
    name_en:       'Дъска с меса за двама',
    price:         39.00,
    price_unit:    null,
    weight:        '1000 г',
    description_bg:'пилешко филе, свинско шишче, пилешко шишче, бифтек, селска наденица',
    allergens:     [],
    image:         'menu-images/Дъска с меса за двама.png',
  },
  {
    id:            'svinska-vratna-parzhola',
    category:      'bbq-meat',
    name_bg:       'Свинска вратна пържола',
    name_en:       'Свинска вратна пържола',
    price:         17.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'свинска вратна пържола, пържени картофи, дзадзики',
    allergens:     ['milk'],
    image:         'menu-images/Свинска вратна пържола.png',
  },
  {
    id:            'suvlaki-miks',
    category:      'bbq-meat',
    name_bg:       'Сувлаки микс',
    name_en:       'Сувлаки микс',
    price:         19.90,
    price_unit:    null,
    weight:        '450 г',
    description_bg:'свинско месо, пилешко месо, питка, дзадзики, магданоз',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Сувлаки микс.png',
  },
  {
    id:            'suvlaki-teleshko',
    category:      'bbq-meat',
    name_bg:       'Телешко сувлаки',
    name_en:       'Телешко сувлаки',
    price:         21.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'телешко месо, питка, сирене фета, чушки, маслини',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Телешко сувлаки.png',
  },
  {
    id:            'selska-nadenitsa',
    category:      'bbq-meat',
    name_bg:       'Селска наденица',
    name_en:       'Селска наденица',
    price:         17.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'наденица, чери домати, мащерка, дзадзики',
    allergens:     ['milk'],
    image:         'menu-images/Селска наденица.png',
  },
  {
    id:            'teleshka-parzhola',
    category:      'bbq-meat',
    name_bg:       'Телешка пържола',
    name_en:       'Телешка пържола',
    price:         19.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешко месо, масло, розмарин',
    allergens:     ['milk'],
    image:         'menu-images/Телешка пържола.png',
  },
  {
    id:            'agneshki-rebra',
    category:      'bbq-meat',
    name_bg:       'Агнешки ребра',
    name_en:       'Агнешки ребра',
    price:         19.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'агнешки ребра, мед, сусам, чери домати',
    allergens:     ['sesame'],
    image:         'menu-images/Агнешки ребра.png',
  },
  {
    id:            'agneshki-kebap',
    category:      'bbq-meat',
    name_bg:       'Агнешки кебап',
    name_en:       'Агнешки кебап',
    price:         19.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'агнешка кайма, лук, подправки',
    allergens:     [],
    image:         'menu-images/Агнешки кебап.png',
  },

  // ── НА ТИГАН ──────────────────────────────────────────────────────────────

  {
    id:            'pileshki-kystcheta-rozmarin',
    category:      'pan-meat',
    name_bg:       'Пилешки късчета с розмарин, гъби и горчица',
    name_en:       'Пилешки късчета с розмарин, гъби и горчица',
    price:         17.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'пилешко месо, гъби, горчица, сметана, розмарин',
    allergens:     ['milk', 'mustard'],
    image:         'menu-images/Пилешки късчета с розмарин гъби и горчица.png',
  },
  {
    id:            'svinski-kystcheta-chushki',
    category:      'pan-meat',
    name_bg:       'Свински късчета с чушки и мащерка',
    name_en:       'Свински късчета с чушки и мащерка',
    price:         18.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'свинско месо, чушки, мащерка, лимон',
    allergens:     [],
    image:         'menu-images/Свински късчета с чушки и мащерка.png',
  },
  {
    id:            'teleshki-drob-karameliziran-luk',
    category:      'pan-meat',
    name_bg:       'Телешки дроб с карамелизиран лук',
    name_en:       'Телешки дроб с карамелизиран лук',
    price:         16.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'телешки дроб, карамелизиран лук, гъби, лимон',
    allergens:     [],
    image:         'menu-images/Телешки дроб с карамелизиран лук.png',
  },

  // ── ПАСТА И РИЗОТО ────────────────────────────────────────────────────────

  {
    id:            'papadele-sas-somga',
    category:      'pasta',
    name_bg:       'Папарделе със сьомга',
    name_en:       'Папарделе със сьомга',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'сметана, чери домати, пушена сьомга, пармезан, мак',
    allergens:     ['gluten', 'fish', 'milk'],
    image:         'menu-images/Папарделе със сьомга.png',
  },
  {
    id:            'papadele-s-teleshko',
    category:      'pasta',
    name_bg:       'Папарделе с телешко',
    name_en:       'Папарделе с телешко',
    price:         17.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'папарделе, телешко месо, доматен сос, пармезан, магданоз',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Папарделе с телешко.png',
  },
  {
    id:            'lingvini-salsa-sos',
    category:      'pasta',
    name_bg:       'Лингуини със салса сос',
    name_en:       'Лингуини със салса сос',
    price:         13.90,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'домати, пармезан',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Лингуини със салса сос.png',
  },
  {
    id:            'rizoto-s-pileshko-i-zelenchutsi',
    category:      'pasta',
    name_bg:       'Ризото с пилешко и зеленчуци',
    name_en:       'Ризото с пилешко и зеленчуци',
    price:         16.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'ориз, пилешко месо, гъби, чушки, пармезан',
    allergens:     ['milk'],
    image:         'menu-images/Ризото с пилешко и зеленчуци.png',
  },
  {
    id:            'rizoto-s-morski-darove',
    category:      'pasta',
    name_bg:       'Ризото с морски дарове',
    name_en:       'Ризото с морски дарове',
    price:         28.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'ориз, скариди, миди, калмари, зехтин',
    allergens:     ['crustaceans', 'molluscs'],
    image:         'menu-images/Ризото с морски дарове.png',
  },
  {
    id:            'kritaroto-s-morski-darove',
    category:      'pasta',
    name_bg:       'Критарото с морски дарове',
    name_en:       'Критарото с морски дарове',
    price:         28.90,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'скариди, миди, калмари, салца сос, босилек',
    allergens:     ['gluten', 'crustaceans', 'molluscs'],
    image:         'menu-images/Критарото с морски дарове.png',
  },
  {
    id:            'pasta-sas-skaridi',
    category:      'pasta',
    name_bg:       'Паста със скариди',
    name_en:       'Паста със скариди',
    price:         27.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'скариди, чери домати, салца сос, босилек',
    allergens:     ['gluten', 'crustaceans'],
    image:         'menu-images/Паста със скариди.png',
  },
  {
    id:            'pene-s-pileshko-i-smetana',
    category:      'pasta',
    name_bg:       'Пене с пилешко и сметана',
    name_en:       'Пене с пилешко и сметана',
    price:         16.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'чушки, гъби, сметанов сос, естрагон',
    allergens:     ['gluten', 'milk'],
    image:         'menu-images/Пене с пилешко и сметана.png',
  },
  {
    id:            'taliateli-pileshko-dizhon',
    category:      'pasta',
    name_bg:       'Талиатели с пилешко филе и сос \'Дижон\'',
    name_en:       'Талиатели с пилешко филе и сос \'Дижон\'',
    price:         19.90,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'талиатели, пилешко филе, сос Дижон, сметана',
    allergens:     ['gluten', 'milk', 'mustard'],
    image:         'menu-images/Талиатели с пилешко филе и сос Дижон.png',
  },

  // ── РИБИ ──────────────────────────────────────────────────────────────────

  {
    id:            'gavros-na-tigan',
    category:      'fish',
    name_bg:       'Гаврос на тиган',
    name_en:       'Гаврос на тиган',
    price:         15.00,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'гаврос, брашно, лимон, магданоз',
    allergens:     ['fish', 'gluten'],
    image:         'menu-images/Гаврос на тиган.png',
  },
  {
    id:            'kalmari-na-tigan',
    category:      'fish',
    name_bg:       'Калмари на тиган',
    name_en:       'Калмари на тиган',
    price:         22.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'калмари, брашно, лимон, дзадзики',
    allergens:     ['gluten', 'milk', 'molluscs'],
    image:         'menu-images/Калмари на тиган.png',
  },
  {
    id:            'palnен-kalmar',
    category:      'fish',
    name_bg:       'Пълнен калмар',
    name_en:       'Пълнен калмар',
    price:         24.60,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'домати, сирене фета, гауда, каперси',
    allergens:     ['milk', 'molluscs'],
    image:         'menu-images/Пълнен калмар.png',
  },
  {
    id:            'oktopod-na-skara',
    category:      'fish',
    name_bg:       'Октопод на скара',
    name_en:       'Октопод на скара',
    price:         29.00,
    price_unit:    null,
    weight:        '150 г',
    description_bg:'октопод, зехтин, чесън, лимон',
    allergens:     ['molluscs'],
    image:         'menu-images/Октопод на скара.png',
  },
  {
    id:            'skaridi-na-skara',
    category:      'fish',
    name_bg:       'Скариди на скара',
    name_en:       'Скариди на скара',
    price:         24.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'скариди, зехтин, чери домати, магданоз, лимон',
    allergens:     ['crustaceans'],
    image:         'menu-images/Скариди на скара.png',
  },
  {
    id:            'pushena-skumriya',
    category:      'fish',
    name_bg:       'Пушена скумрия',
    name_en:       'Пушена скумрия',
    price:         15.00,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'пушена скумрия, лук, лимон, магданоз',
    allergens:     ['fish'],
    image:         'menu-images/Пушена скумрия.png',
  },
  {
    id:            'marinovan-gavros',
    category:      'fish',
    name_bg:       'Маринован гаврос',
    name_en:       'Маринован гаврос',
    price:         15.00,
    price_unit:    null,
    weight:        '200 г',
    description_bg:'гаврос, зехтин, лук, лимон, магданоз',
    allergens:     ['fish'],
    image:         'menu-images/Маринован гаврос.png',
  },
  {
    id:            'skaridi-na-tigan',
    category:      'fish',
    name_bg:       'Скариди на тиган',
    name_en:       'Скариди на тиган',
    price:         24.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'скариди, зехтин, чери домати, лимон, магданоз',
    allergens:     ['crustaceans'],
    image:         'menu-images/Скариди на тиган.png',
  },
  {
    id:            'kalmar-na-plocha',
    category:      'fish',
    name_bg:       'Калмар на плоча',
    name_en:       'Калмар на плоча',
    price:         22.00,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'калмар, зехтин, лимон, дзадзики',
    allergens:     ['milk', 'molluscs'],
    image:         'menu-images/Калмар на плоча.png',
  },
  {
    id:            'plato-s-morski-darove',
    category:      'fish',
    name_bg:       'Плато с морски дарове',
    name_en:       'Плато с морски дарове',
    price:         68.90,
    price_unit:    null,
    weight:        '600 г',
    description_bg:'гаврос, калмар, скариди, миди, октопод',
    allergens:     ['fish', 'crustaceans', 'molluscs'],
    image:         'menu-images/plato-morski-darove.png',
  },
  {
    id:            'barbun',
    category:      'fish',
    name_bg:       'Барбун',
    name_en:       'Барбун',
    price:         32.50,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'барбун, зехтин, лимон, чесън, магданоз',
    allergens:     ['fish'],
    image:         'menu-images/barbun.png',
  },
  {
    id:            'lavrak-na-skara',
    category:      'fish',
    name_bg:       'Лаврак на скара',
    name_en:       'Лаврак на скара',
    price:         8.00,
    price_unit:    '100 г',
    weight:        '400 г',
    description_bg:'лаврак, картофи, спанак, чери домати, зехтин, лимон',
    allergens:     ['fish'],
    image:         'menu-images/Лаврак на скара.png',
  },
  {
    id:            'chipura',
    category:      'fish',
    name_bg:       'Ципура',
    name_en:       'Ципура',
    price:         8.00,
    price_unit:    '100 г',
    weight:        '450 г',
    description_bg:'ципура, рукола, червена чушка, лимон, зехтин',
    allergens:     ['fish'],
    image:         'menu-images/Ципура.png',
  },
  {
    id:            'chipura-diva',
    category:      'fish',
    name_bg:       'Ципура дива',
    name_en:       'Ципура дива',
    price:         10.00,
    price_unit:    '100 г',
    weight:        '500 г',
    description_bg:'ципура дива, картофи, розмарин, лимон, зехтин',
    allergens:     ['fish'],
    image:         'menu-images/Ципура дива.png',
  },
  {
    id:            'somga-na-skara',
    category:      'fish',
    name_bg:       'Сьомга на скара',
    name_en:       'Сьомга на скара',
    price:         28.90,
    price_unit:    null,
    weight:        '300 г',
    description_bg:'сьомга, зехтин, лимон, розмарин',
    allergens:     ['fish'],
    image:         'menu-images/Сьомга на скара.png',
  },
  {
    id:            'gavros-na-skara',
    category:      'fish',
    name_bg:       'Гаврос на скара',
    name_en:       'Гаврос на скара',
    price:         12.90,
    price_unit:    null,
    weight:        '250 г',
    description_bg:'гаврос, брашно, лимон, рукола, магданоз',
    allergens:     ['fish', 'gluten'],
    image:         'menu-images/Гаврос на скара.png',
  },
  {
    id:            'pastarva-na-tigan',
    category:      'fish',
    name_bg:       'Пъстърва на тиган',
    name_en:       'Пъстърва на тиган',
    price:         22.00,
    price_unit:    null,
    weight:        '350 г',
    description_bg:'пъстърва, зехтин, лимон, розмарин, домати',
    allergens:     ['fish'],
    image:         'menu-images/Пъстърва на тиган.png',
  },
  {
    id:            'zadusheni-midi',
    category:      'fish',
    name_bg:       'Задушени миди',
    name_en:       'Задушени миди',
    price:         16.00,
    price_unit:    null,
    weight:        '400 г',
    description_bg:'миди, зехтин, лимон, чушки, магданоз',
    allergens:     ['molluscs'],
    image:         'menu-images/Задушени миди.png',
  },

];
