/**
 * Inline the generated Tailwind CSS into each page.
 *
 * The compiled stylesheet is ~10KB — small enough that fetching it as a
 * separate render-blocking request costs more than it saves. On throttled
 * mobile the extra round trip measured ~280ms before first paint, which is
 * pure LCP delay. Inlining removes the request entirely, and matches the
 * project's existing "all styles inline" convention.
 *
 * Run via `npm run build:css` (which regenerates the CSS first).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CSS = fs.readFileSync(path.join(ROOT, 'css', 'tavernaki.css'), 'utf8').trim();

const START = '<!-- TAILWIND-INLINE:START — generated by npm run build:css; do not edit by hand -->';
const END = '<!-- TAILWIND-INLINE:END -->';
const LINK = '<link rel="stylesheet" href="/css/tavernaki.css">';

const FILES = ['index.html', '404.html', 'pages/menu.html', 'pages/about.html', 'pages/contact.html', 'pages/parties.html'];

const block = `${START}\n    <style>${CSS}</style>\n    ${END}`;

for (const file of FILES) {
  const full = path.join(ROOT, file);
  let html = fs.readFileSync(full, 'utf8');

  if (html.includes(START)) {
    const re = new RegExp(`${START.replace(/[.*+?^${}()|[\]\—]/g, '\$&')}[\s\S]*?${END}`);
    html = html.replace(re, block);
  } else if (html.includes(LINK)) {
    html = html.replace(LINK, block);
  } else {
    console.log(`  ! ${file}: no stylesheet link or existing marker found — skipped`);
    continue;
  }

  fs.writeFileSync(full, html);
  console.log(`  + ${file}: inlined ${(CSS.length / 1024).toFixed(1)}KB`);
}
