/**
 * Pre-render the menu into pages/menu.html.
 *
 * Why: renderMenu() built all 85 dish cards client-side, so the served HTML
 * contained zero dish names. The menu is the site's most commercially valuable
 * content and it was invisible to the first indexing wave — and the grid
 * inflating from empty to 85 cards was the page's main layout shift.
 *
 * This emits the same markup renderMenu() produces (Bulgarian — the indexed
 * language) straight into the HTML, plus the Menu/MenuSection/MenuItem JSON-LD
 * that renderMenuSchema() used to inject at runtime.
 *
 * Cards keep their data-dish-id, so applyLang() still swaps names and
 * descriptions on the EN toggle exactly as before. renderMenu() detects the
 * pre-rendered cards and skips re-creating them.
 *
 * Run once after changing menu-data.js, then commit the output:
 *   node _tools/prerender-menu.mjs
 *
 * Follows the same "generate, commit the result, no build step in deploy"
 * pattern as _tools/generate-menu.py.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const MENU_HTML = path.join(ROOT, 'pages', 'menu.html');

const START = '<!-- PRERENDERED-MENU:START — generated by _tools/prerender-menu.mjs; do not edit by hand -->';
const END = '<!-- PRERENDERED-MENU:END -->';
const SCHEMA_START = '<!-- PRERENDERED-MENU-SCHEMA:START — generated by _tools/prerender-menu.mjs; do not edit by hand -->';
const SCHEMA_END = '<!-- PRERENDERED-MENU-SCHEMA:END -->';

// --- load menu-data.js (it assigns to window.menuData) -----------------------

const dataSrc = fs.readFileSync(path.join(ROOT, 'js', 'menu-data.js'), 'utf8');
const sandbox = { window: {} };
new Function('window', dataSrc)(sandbox.window);
const dishes = sandbox.window.menuData;
if (!Array.isArray(dishes) || dishes.length === 0) throw new Error('menu-data.js produced no dishes');

// --- mirrored from pages/menu.html -----------------------------------------

const ALLERGEN_META = {
  gluten: 'Глутен', crustaceans: 'Ракообразни', eggs: 'Яйца', fish: 'Риба',
  peanuts: 'Фъстъци', soya: 'Соя', milk: 'Мляко', nuts: 'Ядки',
  mustard: 'Синап', sulphites: 'Сулфити', sesame: 'Сусам', molluscs: 'Мекотели',
  celery: 'Целина', lupin: 'Лупина',
};

const CATEGORY_SCHEMA_NAMES = {
  salads: 'Salads', starters: 'Starters', appetizers: 'Appetizers',
  specialties: 'Specialties', 'bbq-meat': 'Grilled & Meat Dishes',
  'pan-meat': 'Pan-Fried Dishes', pasta: 'Pasta & Risotto', fish: 'Fish & Seafood',
};
const CATEGORY_ORDER = ['salads', 'starters', 'appetizers', 'specialties', 'bbq-meat', 'pan-meat', 'pasta', 'fish'];

// --- helpers ----------------------------------------------------------------

const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const escAttr = (s) => esc(s).replace(/"/g, '&quot;');

const webpPath = (image) =>
  image ? image.replace('menu-images/', 'menu-images-webp/').replace('.png', '.webp') : null;

function priceDisplay(dish) {
  if (dish.price == null) return dish.price_unit ? `— / ${dish.price_unit}` : '—';
  const eur = (dish.price / 1.95583).toFixed(2).replace('.', ',');
  const bgn = dish.price.toFixed(2).replace('.', ',');
  return dish.price_unit ? `${eur} € (${bgn} лв.) / ${dish.price_unit}` : `${eur} € (${bgn} лв.)`;
}

/** Intrinsic dimensions, so the browser knows each image's real aspect ratio. */
const dimsCache = new Map();
async function dimensions(rel) {
  if (dimsCache.has(rel)) return dimsCache.get(rel);
  let dims = null;
  try {
    const meta = await sharp(path.join(ROOT, decodeURIComponent(rel))).metadata();
    dims = { width: meta.width, height: meta.height };
  } catch {
    dims = null; // image missing — emit without dimensions rather than guessing
  }
  dimsCache.set(rel, dims);
  return dims;
}

// --- build the cards --------------------------------------------------------

const cards = [];
let missingImages = 0;

// Every dish card sits below the full-viewport page hero, and that hero is the
// measured LCP element. Loading dish images eagerly only steals bandwidth from
// it — measured ~450ms worse LCP on throttled mobile — so they all stay lazy.
const EAGER_COUNT = 0;
let eagerUsed = 0;

for (const dish of dishes) {
  const name = dish.name_bg;
  const img = webpPath(dish.image);
  const allergens = Array.isArray(dish.allergens) ? dish.allergens : [];

  const allergenIcons = allergens
    .map((key) => {
      const label = ALLERGEN_META[key];
      if (!label) return '';
      return (
        `<span class="allergen-icon" title="${escAttr(label)}">` +
        `<img src="brand_assets/allergen-icons/${key}.webp" width="26" height="26" alt="${escAttr(label)}" loading="lazy">` +
        `</span>`
      );
    })
    .join('');

  let imgHTML;
  if (img) {
    const dims = await dimensions(img);
    if (!dims) missingImages++;
    const sizeAttrs = dims ? ` width="${dims.width}" height="${dims.height}"` : '';
    const eager = eagerUsed < EAGER_COUNT;
    const loadAttrs = eager
      ? ` loading="eager" decoding="async"${eagerUsed === 0 ? ' fetchpriority="high"' : ''}`
      : ` loading="lazy" decoding="async"`;
    if (eager) eagerUsed++;
    imgHTML = `<img src="${escAttr(img)}" alt="${escAttr(name)}"${sizeAttrs}${loadAttrs}>`;
  } else {
    imgHTML = `<div class="dish-placeholder" role="img" aria-label="${escAttr(name)}"></div>`;
  }

  const desc = dish.description_bg;

  cards.push(
    `<div class="dish-card" data-category="${escAttr(dish.category)}" data-dish-id="${escAttr(dish.id)}">` +
      `<div class="dish-img-wrap">` +
        imgHTML +
        `<div class="absolute inset-0" style="background:linear-gradient(to top,rgba(7,21,16,0.55) 0%,transparent 60%);pointer-events:none;"></div>` +
        `<span class="dish-price">${esc(priceDisplay(dish))}</span>` +
      `</div>` +
      `<div class="dish-body">` +
        `<h3 class="dish-name">${esc(name)}</h3>` +
        (desc ? `<p class="dish-desc">${esc(desc)}</p>` : '') +
        `<div class="dish-footer">` +
          `<span class="dish-weight" data-weight="${escAttr(dish.weight || '')}">${esc(dish.weight || '')}</span>` +
          (allergenIcons ? `<div class="dish-allergens">${allergenIcons}</div>` : `<div></div>`) +
        `</div>` +
      `</div>` +
    `</div>`
  );
}

// --- build the schema -------------------------------------------------------

const menuSchema = {
  '@context': 'https://schema.org',
  '@type': 'Menu',
  '@id': 'https://www.tavernaki-plovdiv.com/menu#menu',
  name: 'Tavernaki Menu',
  inLanguage: 'en',
  hasMenuSection: CATEGORY_ORDER.map((cat) => ({
    '@type': 'MenuSection',
    name: CATEGORY_SCHEMA_NAMES[cat],
    hasMenuItem: dishes
      .filter((d) => d.category === cat)
      .map((d) => {
        const item = { '@type': 'MenuItem', name: d.name_en, description: d.description_en };
        if (d.price != null) {
          item.offers = { '@type': 'Offer', price: d.price.toFixed(2), priceCurrency: 'BGN' };
        }
        return item;
      }),
  })),
};

// --- splice into menu.html --------------------------------------------------

let html = fs.readFileSync(MENU_HTML, 'utf8');

const cardsBlock = `\n${START}\n${cards.join('\n')}\n${END}\n            `;

if (html.includes(START)) {
  html = html.replace(
    new RegExp(`${START.replace(/[.*+?^${}()|[\]\\—]/g, '\\$&')}[\\s\\S]*?${END}`),
    `${START}\n${cards.join('\n')}\n${END}`
  );
} else if (html.includes('<div id="dish-grid"></div>')) {
  html = html.replace('<div id="dish-grid"></div>', `<div id="dish-grid">${cardsBlock}</div>`);
} else {
  throw new Error('Could not find #dish-grid container or existing pre-render markers in menu.html');
}

const schemaBlock =
  `${SCHEMA_START}\n    <script type="application/ld+json" data-menu-schema>\n` +
  JSON.stringify(menuSchema) +
  `\n    </script>\n    ${SCHEMA_END}`;

if (html.includes(SCHEMA_START)) {
  html = html.replace(
    new RegExp(`${SCHEMA_START.replace(/[.*+?^${}()|[\]\\—]/g, '\\$&')}[\\s\\S]*?${SCHEMA_END}`),
    schemaBlock
  );
} else {
  // Place it right after the existing BreadcrumbList JSON-LD block
  const bc = html.match(/<script type="application\/ld\+json">[\s\S]*?BreadcrumbList[\s\S]*?<\/script>/);
  if (!bc) throw new Error('Could not find the BreadcrumbList JSON-LD block to anchor the Menu schema after');
  html = html.replace(bc[0], `${bc[0]}\n    ${schemaBlock}`);
}

fs.writeFileSync(MENU_HTML, html);

const withImages = dishes.filter((d) => d.image).length;
console.log(`Pre-rendered ${cards.length} dish cards into pages/menu.html`);
console.log(`  categories:        ${CATEGORY_ORDER.length}`);
console.log(`  images sized:      ${withImages - missingImages}/${withImages}`);
if (missingImages) console.log(`  WARNING: ${missingImages} image(s) could not be measured — emitted without width/height`);
console.log(`  menu schema items: ${menuSchema.hasMenuSection.reduce((a, s) => a + s.hasMenuItem.length, 0)}`);
